# Generated by Django 3.0.7 on 2020-06-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_auto_20200629_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
