# Generated by Django 3.0.7 on 2020-06-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Venues",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venue", models.CharField(max_length=255)),
                ("capacity", models.IntegerField(max_length=255)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=10)),
            ],
        ),
    ]
