# Generated by Django 3.0.7 on 2020-06-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Venues",
            new_name="Venue",
        ),
    ]
